version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    container_name: python
    restart: always
    env_file:
      - .env
    build: ./requirements/python

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
